-- Starter content for a fresh project. Run after the migration (SQL Editor → paste → Run).
-- Everything here is editable in /admin; re-running replaces existing content.
begin;
truncate public.site_profile, public.projects, public.experiences, public.skills, public.certifications, public.testimonials, public.achievements, public.posts restart identity;
insert into public.site_profile (name, title, tagline, hero_text, bio, location, email, avatar_url, resume_url, available_for_work, socials, now_building) values
  ('Harshit Verma', 'Full Stack Software Developer', 'Elite engineering for modern digital products.', 'I design and ship fast, accessible, AI-native products — from pixel-perfect interfaces to the APIs and databases that power them.', 'I''m a full stack engineer based in New Delhi who cares about the entire lifecycle of a product: the problem, the architecture, the interface and the numbers after launch. I build with Next.js, Node.js, Supabase and cloud-native tooling, and I increasingly weave LLMs into products where they genuinely remove friction. Currently building at Instinctive Studio.', 'New Delhi, India', 'harshit2005verma@gmail.com', '/images/profile.jpeg', '/resume.pdf', true, '{"github":"https://github.com/Harshit-verma-25","linkedin":"https://www.linkedin.com/in/harshit-verma-533428284/","instagram":"https://www.instagram.com/_harshit.25_/"}'::jsonb, '{"company":"Instinctive Studio","role":"Full Stack Developer","summary":"Shipping production web platforms for clients end-to-end — product discovery, system design, Next.js frontends, Node.js services and cloud deployments.","items":["Multi-tenant dashboards with role-based access","AI-assisted workflows powered by LLM APIs","Design-system driven component libraries","Performance budgets & Core Web Vitals monitoring"]}'::jsonb);

insert into public.projects (slug, title, tagline, description, category, tags, tech, cover_image, images, video_url, github_url, live_url, featured, order_index, year, accent, case_study) values
  ('quyl', 'Quyl', 'An education ecosystem connecting students, mentors and institutions.', 'Quyl is an EdTech platform that brings courses, live mentorship, assessments and institution dashboards into one cohesive ecosystem, so learning, feedback and progress tracking stop living in five different tools.', 'EdTech', array['EdTech', 'Full Stack', 'SaaS']::text[], array['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Supabase', 'Tailwind CSS']::text[], null, '{}', null, 'https://github.com/Harshit-verma-25', null, true, 1, 2025, '#06B6D4', '{"problem":"Students, mentors and institutions were juggling separate tools for content, scheduling, assessments and reporting. Context got lost between them and nobody had a single view of a learner''s progress.","research":"Interviewed students and mentors, mapped every hand-off in a typical week and found that most friction came from switching tools and re-entering the same data. The core insight: progress should be a first-class, shared object — not a spreadsheet exported at the end of term.","architecture":"A Next.js App Router frontend with server components for fast, SEO-friendly course pages; a PostgreSQL schema modelling institutions → cohorts → learners with row-level security; realtime channels for live sessions; and background jobs for grading and notifications.","challenges":[{"title":"Multi-tenant isolation","detail":"Institutions must never see each other''s data. Solved with tenant-scoped RLS policies enforced in the database, not only in the API layer."},{"title":"Realtime at a sensible cost","detail":"Live classes needed presence and chat without a dedicated socket server. Supabase Realtime channels scoped per session kept it simple and cheap."},{"title":"Role-aware UI","detail":"Students, mentors and admins see very different products. A shared design system with role-gated route groups kept one codebase coherent."}],"features":["Course builder with rich content blocks","Live mentorship sessions with presence","Assessments with automated grading","Institution analytics dashboards","Role-based access for students, mentors & admins"],"results":["One place for content, sessions, assessments and progress","Tenant isolation enforced at the database layer"],"metrics":[]}'::jsonb),
  ('visioncoach', 'VisionCoach', 'An AI coach that watches your form and talks you through it in real time.', 'VisionCoach combines computer vision with an LLM coaching layer: it tracks body pose from a camera stream, scores form against exercise-specific rules, and turns the analysis into natural, spoken feedback.', 'AI', array['AI', 'Full Stack']::text[], array['Next.js', 'TypeScript', 'MediaPipe', 'Gemini', 'Node.js', 'Firebase']::text[], null, '{}', null, 'https://github.com/Harshit-verma-25', null, true, 2, 2025, '#8B5CF6', '{"problem":"Home workouts lack feedback. Without a coach, people repeat bad form until it causes injury — and generic workout videos can''t see what you''re doing.","research":"Benchmarked on-device pose estimation models for latency on mid-range laptops and phones, and studied how human coaches phrase corrections: short, positive and one cue at a time.","architecture":"Pose estimation runs in the browser so video never leaves the device. Landmarks feed a deterministic rules engine that scores each rep; only compact, structured summaries are sent to an LLM that generates the coaching cue, which is spoken back with text-to-speech.","architecture_nodes":[{"id":"cam","label":"Camera Stream","group":"input"},{"id":"pose","label":"Pose Estimation","group":"vision"},{"id":"feat","label":"Feature Extractor","group":"vision"},{"id":"rules","label":"Form Rules Engine","group":"logic"},{"id":"llm","label":"LLM Coach","group":"ai"},{"id":"tts","label":"Voice Feedback","group":"output"},{"id":"db","label":"Session Store","group":"data"},{"id":"dash","label":"Progress Dashboard","group":"output"}],"challenges":[{"title":"Latency budget","detail":"Feedback later than ~300ms feels disconnected. Keeping vision on-device and sending only summaries to the LLM kept the loop tight."},{"title":"Hallucination-free coaching","detail":"The LLM never judges form itself — the rules engine does. The model only rephrases verified findings into friendly cues."},{"title":"Privacy","detail":"No raw video is uploaded. Only anonymised rep metrics are stored for progress tracking."}],"features":["Real-time pose tracking in the browser","Rep counting and per-rep form scoring","Spoken, context-aware coaching cues","Session history and progress dashboard"],"results":["Video stays on-device by design","Coaching grounded in deterministic scoring"],"metrics":[]}'::jsonb),
  ('skygaze-india', 'Skygaze India', 'Astronomy for everyone — what''s in the Indian night sky, tonight.', 'Skygaze India turns astronomy data into an approachable experience: upcoming celestial events, ISS passes and sky conditions localised for Indian cities, wrapped in an immersive, space-themed interface.', 'Full Stack', array['Full Stack', 'Cloud']::text[], array['React', 'Three.js', 'Node.js', 'Express', 'AWS']::text[], null, '{}', null, 'https://github.com/Harshit-verma-25', null, true, 3, 2024, '#6366F1', '{"problem":"Most astronomy apps are built for Western audiences and assume dark skies. Indian stargazers need city-specific timings and realistic visibility guidance.","research":"Collected feedback from amateur astronomy groups and found that ''is it worth going outside tonight?'' was the question that mattered most.","architecture":"An Express API aggregates and caches public astronomy and weather data per city, a React client renders the sky with Three.js, and scheduled jobs pre-compute nightly event feeds.","challenges":[{"title":"Upstream rate limits","detail":"Aggregated sources through a caching layer with per-city TTLs."},{"title":"Rendering thousands of stars","detail":"Used instanced points and a single draw call to keep the sky at 60fps on mobile."}],"features":["City-based event calendar","ISS pass predictions","Visibility score for tonight","Interactive 3D sky"],"results":["Localised astronomy for Indian cities","Smooth 3D rendering on mobile"],"metrics":[]}'::jsonb),
  ('kahaanibot', 'KahaaniBot', 'An AI storyteller that writes and illustrates bedtime stories in Hindi and English.', 'KahaaniBot lets kids and parents co-create stories: pick characters, a setting and a moral, and the bot writes a chaptered, age-appropriate story in Hindi or English with illustrations and read-aloud.', 'AI', array['AI', 'SaaS']::text[], array['Next.js', 'OpenAI', 'Gemini', 'Supabase', 'Tailwind CSS']::text[], null, '{}', null, 'https://github.com/Harshit-verma-25', null, true, 4, 2024, '#F472B6', '{"problem":"Parents want fresh, safe, culturally familiar stories — in the language their children speak at home.","research":"Tested prompts with parents and found that structure (characters → setting → moral) produced far more consistent stories than free-form prompts.","architecture":"A guided story builder produces a structured prompt; LLM output is streamed chapter by chapter, passed through a safety filter, and stored in Supabase so families can build a personal library.","challenges":[{"title":"Child safety","detail":"Layered moderation: constrained prompts, output filtering and a report button."},{"title":"Bilingual quality","detail":"Prompted natively in Hindi rather than translating English output, which produced more natural stories."}],"features":["Guided story builder","Hindi & English generation","Read-aloud mode","Personal story library"],"results":["Structured prompting for consistent stories","Streaming chapters for instant feedback"],"metrics":[]}'::jsonb),
  ('leave-management-system', 'Leave Management System', 'Corporate leave workflows with approvals, balances and audit trails.', 'A leave management platform for organisations: employees apply in seconds, managers approve from a single queue, and HR gets accurate balances, policies and reports without spreadsheets.', 'SaaS', array['SaaS', 'Full Stack']::text[], array['React', 'Node.js', 'Express', 'PostgreSQL', 'Tailwind CSS']::text[], null, '{}', null, 'https://github.com/Harshit-verma-25', null, false, 5, 2024, '#22C55E', '{"problem":"Leave requests lived in email threads and spreadsheets, so balances drifted and approvals stalled.","research":"Mapped the approval chain across roles and identified multi-level approvals and policy accrual as the core complexity.","architecture":"A state-machine driven request lifecycle (draft → pending → approved/rejected → cancelled) on an Express + PostgreSQL backend, with every transition written to an audit log.","challenges":[{"title":"Multi-level approvals","detail":"Modelled approval chains as data so organisations can configure them without code changes."},{"title":"Accurate balances","detail":"Balances are derived from an append-only ledger instead of a mutable counter."}],"features":["Apply & track requests","Manager approval queue","Policy-based accruals","Audit trail & reports"],"results":["Single source of truth for leave balances","Configurable approval chains"],"metrics":[]}'::jsonb),
  ('portfolio-os', 'Portfolio OS', 'This site — a fast, CMS-driven portfolio with an AI assistant.', 'An open-source, production-grade portfolio built with Next.js 15, Supabase and Framer Motion: a full admin CMS with role-based access, analytics and an AI assistant that answers questions about my work.', 'Open Source', array['Open Source', 'Full Stack', 'AI']::text[], array['Next.js', 'TypeScript', 'Supabase', 'Framer Motion', 'Claude', 'PostHog']::text[], null, '{}', null, 'https://github.com/Harshit-verma-25/Portfolio', null, false, 6, 2026, '#F59E0B', null);

insert into public.experiences (company, position, location, employment_type, start_date, end_date, description, achievements, tech, order_index) values
  ('Instinctive Studio', 'Full Stack Developer', 'New Delhi, India', 'Full-time', '2025-06-01', null, 'Building production web platforms for clients end-to-end, from system design to deployment.', array['Own features across Next.js frontends, Node.js APIs and PostgreSQL schemas', 'Integrate LLM-powered workflows into client products', 'Introduced shared component patterns and performance budgets']::text[], array['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS']::text[], 1),
  ('Instinctive Studio', 'Software Developer Intern', 'New Delhi, India', 'Internship', '2024-12-01', '2025-05-31', 'Joined the product team to build and ship client-facing features.', array['Shipped responsive, accessible UI features for client projects', 'Built REST endpoints and database migrations', 'Converted to a full-time role']::text[], array['React', 'Express', 'Tailwind CSS', 'Firebase']::text[], 2),
  ('Vivekanand Institute of Professional Studies', 'Bachelor of Computer Applications (BCA)', 'New Delhi, India', 'Education', '2023-08-01', '2026-06-30', 'Undergraduate degree in computer applications.', '{}', '{}', 3),
  ('KDB Public School', 'Class 12', 'Ghaziabad, Uttar Pradesh', 'Education', '2022-04-01', '2023-03-31', 'Senior secondary education.', array['Won two gold medals at the Blind Coding event, IMS Ghaziabad (Dec 2022)']::text[], '{}', 4),
  ('Indian Public School', 'Class 10', 'Amritsar, Punjab', 'Education', '2020-04-01', '2021-03-31', 'Wrote my first lines of HTML and fell in love with building for the web.', '{}', '{}', 5);

insert into public.skills (name, category, icon, proficiency, years, order_index) values
  ('React', 'frontend', 'react', 92, 3, 1),
  ('Next.js', 'frontend', 'nextjs', 90, 2.5, 2),
  ('TypeScript', 'frontend', 'typescript', 88, 2.5, 3),
  ('Tailwind CSS', 'frontend', 'tailwind', 94, 3, 4),
  ('Three.js', 'frontend', 'threejs', 72, 1, 5),
  ('Node.js', 'backend', 'nodejs', 86, 2.5, 1),
  ('Express', 'backend', 'express', 85, 2.5, 2),
  ('Python', 'backend', 'python', 75, 3, 3),
  ('PostgreSQL', 'database', 'postgresql', 80, 2, 1),
  ('MySQL', 'database', 'mysql', 78, 3, 2),
  ('AWS', 'cloud', 'aws', 70, 1.5, 1),
  ('Firebase', 'cloud', 'firebase', 82, 2, 2),
  ('Supabase', 'cloud', 'supabase', 85, 1.5, 3),
  ('Gemini', 'ai', 'gemini', 80, 1, 1),
  ('OpenAI', 'ai', 'openai', 82, 1.5, 2),
  ('Vertex AI', 'ai', 'vertexai', 68, 1, 3),
  ('Figma', 'frontend', 'figma', 75, 2, 6),
  ('Git', 'devops', 'git', 88, 3, 1),
  ('Vercel', 'devops', 'vercel', 88, 2, 2),
  ('Docker', 'devops', 'docker', 65, 1, 3);



insert into public.achievements (title, description, date, metric, order_index) values
  ('Double gold — Blind Coding', 'Won two gold medals at the Blind Coding event held at IMS, Ghaziabad.', '2022-12-01', '2× Gold', 1),
  ('Intern → Full-time', 'Converted an internship at Instinctive Studio into a full-time engineering role.', '2025-06-01', 'Full-time', 2);


commit;
