#!/usr/bin/env node
/**
 * Generates supabase/seed.sql from src/lib/data/content.ts so the database starts with
 * exactly the content the site falls back to.  Usage: npm run db:seed:generate
 */
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = readFileSync(join(root, "src/lib/data/content.ts"), "utf8");
const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } });
const tmp = join(mkdtempSync(join(tmpdir(), "seed-")), "content.mjs");
writeFileSync(tmp, outputText);
const c = await import(pathToFileURL(tmp).href);

const lit = (v) => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map(lit).join(", ")}]::text[]`;
  if (typeof v === "object") return `${lit(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const insert = (table, rows, cols) =>
  rows.length
    ? `insert into public.${table} (${cols.join(", ")}) values\n${rows.map((r) => `  (${cols.map((k) => (Array.isArray(r[k]) && r[k].length === 0 ? "'{}'" : lit(r[k]))).join(", ")})`).join(",\n")};\n`
    : "";

const sql = [
  "-- Generated by scripts/generate-seed.mjs — do not edit by hand.",
  "begin;",
  "truncate public.profile, public.projects, public.experiences, public.skills, public.certifications, public.testimonials, public.achievements, public.posts restart identity;",
  insert("profile", [c.profile], ["name", "title", "tagline", "hero_text", "bio", "location", "email", "avatar_url", "resume_url", "available_for_work", "socials", "now_building"]),
  insert("projects", c.projects, ["slug", "title", "tagline", "description", "category", "tags", "tech", "cover_image", "images", "video_url", "github_url", "live_url", "featured", "order_index", "year", "accent", "world", "case_study"]),
  insert("experiences", c.experiences, ["company", "position", "location", "employment_type", "start_date", "end_date", "description", "achievements", "tech", "order_index"]),
  insert("skills", c.skills, ["name", "category", "icon", "proficiency", "years", "order_index"]),
  insert("certifications", c.certifications, ["title", "issuer", "issue_date", "credential_url", "order_index"]),
  insert("testimonials", c.testimonials, ["name", "role", "company", "quote", "avatar_url", "order_index"]),
  insert("achievements", c.achievements, ["title", "description", "date", "metric", "order_index"]),
  insert("posts", c.posts, ["slug", "title", "excerpt", "content", "cover_image", "tags", "status", "published_at", "seo_title", "seo_description"]),
  "commit;",
  "",
].join("\n");

writeFileSync(join(root, "supabase/seed.sql"), sql);
console.log("✓ wrote supabase/seed.sql");
